name: condition
description: This package contains Widgets that will let you show a child Widget based on provided conditions.
version: 0.0.5
author: Stephan E.G. Veenstra <seg.veenstra@gmail.com>
homepage: https://github.com/SEGVeenstra/flutter-package-condition

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
